#!/bin/sh

mkdir -p /proc
mkdir -p /sys
mkdir -p /dev

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo "Hewwo!!!! I'm the PWID one uwu"

while [ true ]; do
    getty -n -l /bin/sh 0 ttyS0
    echo 'Restarting TTY...'
done
reboot -f
